src/Entity/CV.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="ur_cv")
 * @ORM\Entity(repositoryClass="App\Repository\CVRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class CV
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $path;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $originalname;

    /**
     * @ORM\Column(type="boolean")
     */
    private $current;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @Assert\NotBlank(message="Please, upload a file.")
     * @Assert\File(maxSize="100m", maxSizeMessage = "The file is too large ({{ size }})")
     */
    public $file;

    public function getFile()
    {
        return $this->file;
    }

    public function setFile($file)
    {
        $this->file = $file;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(?string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getOriginalname(): ?string
    {
        return $this->originalname;
    }

    public function setOriginalname(string $originalname): self
    {
        $this->originalname = $originalname;

        return $this;
    }

    public function getCurrent(): ?bool
    {
        return $this->current;
    }

    public function setCurrent(bool $current): self
    {
        $this->current = $current;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function  getNewName(){
        $originalName = $this->getOriginalName();
        $position = strripos($originalName,".");
        $extension = substr($originalName,$position+1,strlen($originalName));

        if(trim($this->getName()) != ""){
            $newName = $this->getName().".".$extension;
            return $newName;
        }else{
            return $this->getOriginalName();
        }
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->path;
    }

    protected function getUploadDir()
    {
        return 'cv';
    }

    public function getAbsolutePath()
    {
        return $this->getUploadRootDir().'/'.$this->path;
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../uploads/'.$this->getUploadDir();
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        //Suppression du fichier principal
        $file = $this->getAbsolutePath();
        if (file_exists($file)) {
            unlink($file);
        }
    }

    public function getFilesize(){
        $size = filesize($this->getAbsolutePath()) ;
        return $size;
    }

    public function getFormattedFilesize(){
        $size = $this->getFilesize() ;
        $formattedSize = $size." Bytes";
        if($size >= 1024 && $size < 1024*1024){
            $sizeTemp = $size / 1024;
            $sizeTemp = number_format($sizeTemp, 2, '.', '');
            $formattedSize = $sizeTemp." KB";
        }elseif($size >= 1024*1024 && $size < 1024*1024*1024){
            $sizeTemp = $size / 1024 / 1024;
            $sizeTemp = number_format($sizeTemp, 2, '.', '');
            $formattedSize = $sizeTemp." MB";
        }elseif($size >= 1024*1024*1024){
            $sizeTemp = $size / 1024 / 1024 / 1024;
            $sizeTemp = number_format($sizeTemp, 2, '.', '');
            $formattedSize = $sizeTemp." GB";
        }
        return $formattedSize;
    }
}

src/Form/UserType.php
<?php

// src/Form/UserType.php
namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('email', EmailType::class)
            ->add('password',  PasswordType::class)
            ->add('register',  SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => User::class,
            'csrf_protection' => false,
        ));
    }

    public function getBlockPrefix() {
        return null;
    }
}

src/Controller/Admin/UserController.php
<?php
namespace App\Controller\Admin;

use App\Entity\UserTeam;
use App\Form\UserTeamEditType;
use App\Repository\ParameterRepository;
use App\Repository\UserRepository;
use App\Repository\UserTeamRepository;
use App\Service\PlatformService;
use App\Service\UserService;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class UserController extends AbstractController {

    public function __construct(
        ParameterRepository $parameterRepository,
        UserRepository $userRepository,
        UserTeamRepository $userTeamRepository,
        PlatformService $platformService,
        UserService $userService,
        ObjectManager $em
    )
    {
        $this->parameterRepository = $parameterRepository;
        $this->platformService = $platformService;
        $this->userRepository = $userRepository;
        $this->userTeamRepository = $userTeamRepository;
        $this->userService = $userService;
        $this->em = $em;
    }

    public function index(): Response
    {
        $users = $this->userRepository->findAll();
        $activeUsers = $this->userRepository->findBy(array(
            'enabled' => true
        ));
        $inactiveUsers = $this->userRepository->findBy(array(
            'enabled' => false
        ));

        return $this->render('admin/user/user.html.twig', array(
            'users' => $users,
            'activeUsers' => $activeUsers,
            'inactiveUsers' => $inactiveUsers,
            'view' => 'user',
        ));
    }

    public function admin(): Response
    {
        $users = $this->userRepository->getAdmins();

        return $this->render('admin/user/user_admin.html.twig', array(
            'users' => $users,
            'view' => 'user',
        ));
    }

    public function editUser($user_id)
    {
        $user = $this->userRepository->find($user_id);

        return $this->render('admin/user/user_edit.html.twig', array(
            'user' => $user,
            'view' => 'user',
        ));
    }

    public function toggleAdminState($user_id, Request $request)
    {
        $user = $this->userRepository->find($user_id);
        $response = new Response();

        //set state 0 in error case
        $response->setContent(json_encode(array(
            'state' => 0,
        )));

        if ($user && !$user->isSuperAdmin() && $this->isGranted('ROLE_SUPER_ADMIN')) {
            if($user->isAdmin()){
                $roles = array("ROLE_USER");
            }else{
                $roles = array("ROLE_ADMIN");
            }

            $user->setRoles($roles);
            $this->em->persist($user);
            $this->em->flush();

            $response->setContent(json_encode(array(
                'state' => 1,
                'case' => $user->isAdmin(),
            )));
        }
        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

    public function team(): Response
    {
        //$users = $this->userTeamRepository->findAll();
        $users = $this->userTeamRepository->findOrderBy();
        $publishedUsers = $this->userTeamRepository->findBy(array(
            'published' => true
        ));
        $notPublishedUsers = $this->userTeamRepository->findBy(array(
            'published' => false
        ));

        return $this->render('admin/user/team.html.twig', array(
            'users' => $users,
            'publishedUsers' => $publishedUsers,
            'notPublishedUsers' => $notPublishedUsers,
            'view' => 'user',
        ));
    }

    public function togglePublicationTeam($userTeam_id, Request $request)
    {
        $userTeam = $this->userTeamRepository->find($userTeam_id);

        $response = new Response();
        $response->setContent(json_encode(array(
            'state' => 0,
        )));
        if ($userTeam) {
            if($userTeam->getPublished() == true){
                $userTeam->setPublished(false) ;
            }else{
                $userTeam->setPublished(true) ;
            }

            $this->em->persist($userTeam);
            $this->em->flush();

            $userTeams = $this->userTeamRepository->findAll();
            $publishedUserTeams = $this->userTeamRepository->findBy(array(
                'published' => true,
            ));
            $notPublishedUserTeams = $this->userTeamRepository->findBy(array(
                'published' => false,
            ));

            $response->setContent(json_encode(array(
                'state'                 => 1,
                'case'                  => $userTeam->getPublished(),
                'userTeams'             => $userTeams,
                'publishedUserTeams'    => $publishedUserTeams,
                'notPublishedUserTeams' => $notPublishedUserTeams,
            )));
        }

        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

    public function toggleShowTeam($user_id, Request $request)
    {
        $user = $this->userRepository->find($user_id);

        $response = new Response();
        $response->setContent(json_encode(array(
            'state' => 0,
        )));
        if ($user) {
            if($this->userService->isUserTeam($user)){
                $userTeam = $this->userTeamRepository->findOneBy(array(
                    'user' => $user,
                ));
                $userTeam->setPublished(false);
                $this->em->persist($userTeam);
            }else{
                $userTeam = $this->userTeamRepository->findOneBy(array(
                    'user' => $user,
                ));
                if($userTeam){
                    $userTeam->setPublished(true);
                    $this->em->persist($userTeam);
                }else{
                    $userTeam = new UserTeam();
                    $userTeam->setUser($user);
                    $userTeam->setPublished(true);
                    
                    $lastUserTeam = $this->userTeamRepository->findLastUserTeam('position');
                    $position = 0;
                    if($lastUserTeam){
                        $position = $lastUserTeam->getPosition() + 1;
                    }
                    $userTeam->setPosition($position);
                    
                    $this->em->persist($userTeam);
                }
            }
            $this->em->persist($userTeam);
            $this->em->flush();

            $response->setContent(json_encode(array(
                'state' => 1,
                'case' => $this->userService->isUserTeam($user),
                'position' => $userTeam->getPosition()
            )));
        }

        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

    public function teamPosition(): Response
    {
        $users = $this->userTeamRepository->findOrderBy();

        return $this->render('admin/user/team_position.html.twig', array(
            'users' => $users,
            'view' => 'user',
        ));
    }

    public function savePositionTeam(Request $request): Response
    {
        $order = $request->query->get('order');

        $ids = explode("-", $order);
        $position = 0;
        foreach ($ids as $id){
            $userTeam = $this->userTeamRepository->find($id);
            if($userTeam){
                $position++;
                $userTeam->setPosition($position);
            }
            $this->em->flush();
        }

        $response = new Response();

        $response->setContent(json_encode(array(
            'state' => 1,
            'order' => $order,
        )));

        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

    public function editUserTeam($userTeam_id)
    {
        $userTeam = $this->userTeamRepository->find($userTeam_id);

        return $this->render('admin/user/team_user_edit.html.twig', array(
            'userTeam' => $userTeam,
            'view' => 'user',
        ));
    }

    /*
     * doEdit userTeam
     */
    public function doEditUserTeam($userTeam_id, Request $request)
    {
        $userTeam = $this->userTeamRepository->find($userTeam_id);

        $userTeamTemp = new UserTeam();
        $form = $this->createForm(UserTeamEditType::class, $userTeamTemp);
        $form->handleRequest($request);
        $response = new Response();
        if ($form->isSubmitted() && $form->isValid()) {
            $userTeam->setRole($userTeamTemp->getRole());
            $userTeam->setDescription($userTeamTemp->getDescription());

            $this->em->persist($userTeam);
            $this->em->flush();

            $response->setContent(json_encode(array(
                'state' => 1,
                'role' => $userTeam->getRole(),
                'description' => $userTeam->getDescription(),
            )));
        }else{
            $response->setContent(json_encode(array(
                'state' => 0,
            )));
        }
        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

    /*
     * User Team delete
     */
    public function deleteUserTeam($userTeam_id, Request $request)
    {
        $userTeam = $this->userTeamRepository->find($userTeam_id);

        $response = new Response();
        if ($userTeam) {
            $this->em->remove($userTeam);
            $this->em->flush();

            $userTeams = $this->userTeamRepository->findAll();
            $publishedUserTeams = $this->userTeamRepository->findBy(array(
                'published' => true,
            ));
            $notPublishedUserTeams = $this->userTeamRepository->findBy(array(
                'published' => false,
            ));

            $response->setContent(json_encode(array(
                'state' => 1,
                'id' => $userTeam_id,

templates/user/include/about.html.twig
<div class="cr">
	<div class="ct">
		<div class="pd_10" style="min-height:100px">
			<div class="pd_t10">Inscrit depuis {{ getDateLabel(user.date) }}</div>
			{% if is_granted("IS_AUTHENTICATED_REMEMBERED") and app.user.id == user.id %}
				<div class="sp mg_v5"></div>
				<div><strong>Biographie</strong> <span id="msg_biography"></span></div>
				<div class="sp mg_v5"></div>
				<div class="bloc_editable" style="margin-bottom:1px">
				<div class="bloc_view">
					<div id="ur_view_biography">{{ user.biography }}</div>
				</div>
				<div class="bloc_edit" style="display:none">
					<form action="" name="form_ur_biography" method="post" id="form_ur_biography">
						<div><textarea class="default_textarea" id="ur_area_biography" style="min-height:50px">{{ user.biography }}</textarea></div>
						<input type="submit" style="display:none" value="Enregistrer" />
					</form>
				</div>
				<div class="bloc_action" style="margin-top:5px; border:1px solid transparent">
					<span class="btn_edit standar_button">Modifier</span> 
					<span class="btn_save standar_button" id="btn_save_ur_biography" data-target="{{ path('user_modify_biography') }}" style="display:none">Enregistrer</span>
					<span class="btn_reset standar_button" style="display:none">Annuler</span> 
					<span class="btn_loading" style="display:none;padding:5px;border:1px solid transparent;margin: 0px 5px 0px 0px;">Chargement...</span> 
				</div>
			</div>
			{% else %}
				{% if user.biography | trim != "" %}
					<div class="sp mg_v5"></div>
					<div><strong>Biographie</strong></div>
					<div class="sp mg_v5"></div>
					<div>{{ user.biography }}</div>
				{% endif %}
			{% endif %}
		</div>
	</div>
</div>

templates/user/include/avatar_item.html.twig
<div class="image_item avatar_item {{ classActive }}">
	<span class="delete_image delete_avatar" data-target="{{ path('user_delete_avatar', {'id': avatar.id}) }}"><img src="{{ asset('image/cross_icon.png') }}" alt="x"/></span>
	<img class="user_avatar_popup" data-target="{{ path('user_select_avatar', {'id': avatar.id}) }}" src="{{ avatar.webPath | imagine_filter('116x116') }}" alt="" />
</div>

templates/user/include/comments.html.twig
<div id="list_comment" class="mg_t5">
		<div class="mg_10">
			{% if comments | length == 0%}
				<div class="mg_v20 ta_c">
					<strong>Aucun commentaire à afficher</strong>
				</div>
			{% else %}
				<div>{{ comments | length }} {% if comments | length > 1 %}commentaires{% else %}commentaire{% endif %}.</div>
				{% for comment in comments %}
					{% if comment.post %}
						<div class="user_comment_item">
							<div class="sep"></div>
							<div class="mg_v10">
								<div class="illustration_wrap">
									{% set illustration = postIllustration(comment.post) %}
									<a href="{{ path('blog_post_view', {'slug': comment.post.slug}) }}">
										<img src="{{ illustration | imagine_filter('60x60') }}" />
									</a>
								</div>
								<div class="comment_wrap">
									<div class="mg_b5">Ecrit le {{ getDateLabel(comment.date) }} à {{ comment.date | date('H:i') }}
										sur l'article <a href="{{ path('blog_post_view', {'slug': comment.post.slug}) }}"><strong>{{ comment.post.title }}</strong></a></div>
									<div>{{ comment.comment}}</div>
								</div>
								<div class="both"></div>
							</div>
						</div>
					{% endif %}
					{% if comment.event %}
						<div class="user_comment_item">
							<div class="sep"></div>
							<div class="mg_v10">
								<div class="illustration_wrap">
									{% set illustration = eventIllustration(comment.event) %}
									<a href="{{ path('event_view', {'slug': comment.event.slug}) }}">
										<img src="{{ illustration | imagine_filter('60x60') }}" />
									</a>
								</div>
								<div class="comment_wrap">
									<div class="mg_b5">Ecrit le {{ getDateLabel(comment.date) }} à {{ comment.date | date('H:i') }} sur l'évènement <a href="{{ path('event_view', {'slug': comment.event.slug}) }}"><strong>{{ comment.event.title }}</strong></a></div>
									<div>{{ comment.comment}}</div>
								</div>
								<div class="both"></div>
							</div>
						</div>
					{% endif %}
				{% endfor %}
			{% endif %}
		</div>
	</div>

templates/user/include/evaluations.html.twig
<div id="list_comment" class="mg_t5">
	<div class="mg_10">
		{% if evaluations | length == 0%}
			<div class="mg_v20 ta_c">
				<strong>Aucune évaluation à afficher</strong>
			</div>
		{% else %}
			<div>{{ evaluations | length }} {% if evaluations | length > 1 %}évaluations{% else %}évaluation{% endif %}.</div>
			{% for evaluation in evaluations %}
				<div class="sep"></div>
				<div class="mg_v10">
					<div class="mg_b5">Ecrit le {{ getDateLabel(evaluation.date) }} à {{ evaluation.date | date('H:i') }} sur <a href="{{ path('school_view', {'slug': evaluation.school.slug, 'type': 'evaluation'}) }}"><strong>{{ evaluation.school.name }}</strong></a></div>
					<div>
						<div class="f_l" style="width:50px">
							{% set logo = schoolLogo(evaluation.school) %}
							<span class="f_l" style="display:block;width:32px"><img style="width:50px; height: 50px; border-radius: 5px" src="{{ logo | imagine_filter('50x50') }}" alt="{{ evaluation.school.shortName }}" /></span>
						</div>
						<div style="margin-left:60px">
							<div style="height:26px">
								<div class="f_l" style="padding-top:2px">Notes : </div>
								{% set mark = evaluation.mark/20 %}
								{% for i in 1..5 %}
									{% if i <= mark %}
										<div class="f_l pd_5"><div class="eval_star_view_item selected" data-value="20"></div></div>
									{% else %}
										<div class="f_l pd_5"><div class="eval_star_view_item" data-value="100"></div></div>
									{% endif %}
								{% endfor %}
							</div>
							<div class="mg_b5">
								{{ evaluation.comment | nl2br  }}
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		{% endif %}
	</div>
</div>

templates/user/include/events.html.twig
{% if is_granted("IS_AUTHENTICATED_REMEMBERED") and app.user.id == user.id %}
	<div class="pd_10">
		<span class="create_event standar_button" style="cursor: pointer" data-target="{{ path('event_manager_add_ajax')}}"><img src="{{ asset('image/add_icon.png') }}" style="width:12px; height:auto"> Proposer un évènement</span>
	</div>
	<div class="mg_h10">
		<div class="sp"></div>
	</div>
{% endif %}

{% if events | length == 0 %}
	<div class="mg_v20 ta_c">
		<strong>Aucun évènement à afficher</strong>
	</div>
{% else %}
	<div class="search" data-item-display="block">
		{% if events | length >= 2 %}
			<div class="search_input_cr pd_5 mg_h10 mg_t10">
				<div class="search_input_left">
					<label for="search_input" class="label_search_input">Rechercher :</label> <span class="search_input_wrap"><input type="text" id="search_input" class="search_input"/><!--
				--><span class="search_reset"><i class="fas fa-times"></i></span><!--
						--></span>
				</div>
				<div class="search_input_right">
					<span class="result_state" style="vertical-align: middle">{{ events | length }} résultat{% if events | length > 1 %}s{% endif %}</span>
				</div>
				<div class="both"></div>
			</div>
		{% endif %}
		<div id="et_list"><!--
			{% for event in events %}
				-->{{ include("event/include/event_item.html.twig") }}<!--
			{% endfor %}
		--><div class="both"></div>
		</div>
	</div>
{% endif %}

templates/user/include/posts.html.twig
{% if is_granted("IS_AUTHENTICATED_REMEMBERED") and app.user.id == user.id %}
	<div class="pd_10">
		<span class="create_post standar_button" style="cursor: pointer" data-target="{{ path('blog_manager_add_post_ajax')}}"><img src="{{ asset('image/add_icon.png') }}" style="width:12px; height:auto"> Proposer un article</span>
	</div>
	<div class="mg_h10">
		<div class="sp"></div>
	</div>
{% endif %}

{% if posts | length == 0 %}
	<div class="mg_v20 ta_c">
		<strong>Aucun article à afficher</strong>
	</div>
{% else %}
	<div class="search" data-item-display="block">
		{% if posts | length >= 2 %}
			<div class="search_input_cr pd_5 mg_h10 mg_t10">
				<div class="search_input_left">
					<label for="search_input" class="label_search_input">Rechercher :</label> <span class="search_input_wrap"><input type="text" id="search_input" class="search_input"/><!--
				--><span class="search_reset"><i class="fas fa-times"></i></span><!--
						--></span>
				</div>
				<div class="search_input_right">
					<span class="result_state" style="vertical-align: middle">{{ posts | length }} résultat{% if posts | length > 1 %}s{% endif %}</span>
				</div>
				<div class="both"></div>
			</div>
		{% endif %}
		<div id="list_post"><!--
			{% for post in posts %}
				-->{{ include("blog/include/post_item.html.twig") }}<!--
			{% endfor %}
		--><div class="both"></div>
		</div>
	</div>
{% endif %}

templates/user/include/setting.html.twig
<div class="cr">
	<div class="ct">
		<div class="pd_10" style="min-height:100px">
			<div>
				Gérer votre mot de passe. <div id="msg_password"></div>
			</div>
			<div class="sep"></div>
			<div class="bloc_editable" style="margin-bottom:1px">
				<div class="bloc_view"></div>
				<div class="bloc_edit" style="display:none;">
					<form action="" name="form_ur_password" method="post" id="form_password">
						<div>
							<div><label for="name" class="required">Mot de passe actuel *: </label></div>
							<div><input type="password" id="ur_input_current_password" class="default_input" value="" /></div>
						</div>
						<div>
							<div><label for="name" class="required">Nouveau mot de passe *: </label></div>
							<div><input type="password" id="ur_input_new_password" class="default_input" value="" /></div>
						</div>
						<div>
							<div><label for="name" class="required">Confirmer la saisie *: </label></div>
							<div><input type="password" id="ur_input_repeat_password" class="default_input" value="" /></div>
						</div>
						<input type="submit" style="display:none" value="Enregistrer" />
					</form>
				</div>
				<div class="bloc_action" style="margin:5px 0; border:1px solid transparent">
					<span class="btn_edit standar_button">Modifier</span>
					<span class="btn_save standar_button" id="btn_save_ur_password" data-target="{{ path('user_modify_password') }}" style="display:none">Enregistrer</span>
					<span class="btn_reset standar_button" style="display:none">Annuler</span>
					<span class="btn_loading" style="display:none;padding:5px;border:1px solid transparent;margin: 0px 5px 0px 0px;">Chargement...</span>
				</div>
			</div>
		</div>
	</div>
</div>